# Generated by Django 4.2.7 on 2023-11-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='owner',
            name='dni',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AddField(
            model_name='owner',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
