# Generated by Django 4.2.7 on 2023-11-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_remove_owner_descripcion_owner_dni_owner_vigente'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='edad',
            field=models.IntegerField(default='00'),
        ),
    ]
