# Generated by Django 4.2.7 on 2023-12-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_owner_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='edad',
            field=models.CharField(default='00', max_length=2),
        ),
    ]
