# Generated by Django 4.2.7 on 2023-11-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25)),
                ('Numero', models.IntegerField()),
                ('Generacion', models.CharField(default='', max_length=27)),
                ('Tipo', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
